# This workflow will run scripts pull_by_yourself.sh
#
# To configure this workflow:
#
# 1. Set up secrets in your workspace: 
#    - ALIYUN_USERNAME with aliyun registry username
#    - ALIYUN_PASSWORD with aliyun registry password
#
# 2. Change the values for the ALIYUN_REGISTRY, ALIYUN_NAMESPACE  environment variables (below).

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: willdockerhub
  ALIYUN_USERNAME: willzhmic@outlook.com
  ALIYUN_REGISTRY_URL: registry.cn-shenzhen.aliyuncs.com

jobs:
  get-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Log into aliyun registry
    - name: Login aliyun and docker registry
      run: |
        echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login $ALIYUN_REGISTRY_URL -u $ALIYUN_USERNAME --password-stdin
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

    # pull retag and push images
    - name: get images
      run: sh pull_by_yourself.sh

    - name: list images
      run: |
        docker images --format "{{.Repository}}:{{.Tag}}" | grep $ALIYUN_REGISTRY_URL || true
        docker images --format "{{.Repository}}:{{.Tag}}" | grep $DOCKERHUB_USERNAME || true
