# This workflow will run scripts pull_by_yourself.sh
#
# To configure this workflow:
#
# 1. Set up secrets in your workspace: 
#    - ALIYUN_USERNAME with aliyun registry username
#    - ALIYUN_PASSWORD with aliyun registry password
#
# 2. Change the values for the ALIYUN_REGISTRY, ALIYUN_NAMESPACE  environment variables (below).

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: willdockerhub
  ALI_USERNAME: willzhmic@outlook.com
  ALI_REGISTRY_URL: registry.cn-shenzhen.aliyuncs.com
  ALI_REGISTRY_NAMESPACE: images_mirror

jobs:
  get-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: get images
      env:
        ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login $ALIYUN_REGISTRY -u $ALIYUN_USERNAME -p "ALIYUN_PASSWORD"
        docker login -u $DOCKERHUB_USERNAME -p "DOCKERHUB_PASSWORD"

    # pull retag and push images
    - name: get images
      run: sh pull_by_yourself.sh

    - name: list images
      run: |
        docker images --format "{{.Repository}}:{{.Tag}}" | grep $ALI_REGISTRY_URL
        docker images --format "{{.Repository}}:{{.Tag}}" | grep $DOCKERHUB_USERNAME
